# Generated by Django 5.2.11 on 2026-05-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zinnia", "0006_alter_category_id_alter_entry_id_alter_entry_related"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="entry",
            name="zinnia_entry_status_creat_idx",
        ),
        migrations.RemoveIndex(
            model_name="entry",
            name="zinnia_entry_slug_creat_idx",
        ),
    ]
